/*
Script generated by Aqua Data Studio 19.0.2 on Aug-28-2019 05:14:00 PM
Database: _DEV
Schema: dbo
Objects: TABLE
*/
IF OBJECT_ID('dbo.USER_LIST') IS NOT NULL
DROP TABLE [dbo].[USER_LIST]
GO
CREATE TABLE [dbo].[USER_LIST]  ( 
	[Display_Name]  	varchar(255) NULL,
	[E_Mail_Address]	varchar(255) NULL,
	[AD_Name]       	varchar(255) NULL,
	[QAD_Site]      	varchar(255) NULL,
	[CDC_DEL_FLG]   	bit NULL,
	[CDC_ACT_FLG]   	bit NULL,
	[CDC_CRDT]      	smalldatetime NULL,
	[CDC_UPDT]      	smalldatetime NULL 
	)
GO
